### ISSUE TITLE
Saving the file not updating the TOC anymore

### ISSUE THREAD

**Issue by lguerard** [naokazuterada/MarkdownTOC#127]
Hi,

I haven't noticed that before since I didn't use it before but the TOC used to be updated when saving the file but this doesn't seem to be working anymore for me.

Is there anything to add to the user settings for that ?

Using ST 3.1.1 Build 3176

Thanks.

**Comment by naokazuterada** [comment]
Hi, @lguerard 

> Is there anything to add to the user settings for that ?

No, you don't need anything on settings.

Is there any errors on console?
Please read [Upgrade Guide](https://github.com/naokazuterada/MarkdownTOC/releases/tag/3.0.0) if you didn't.

**Comment by lguerard** [comment]
Hi @naokazuterada ,

Thanks for the fast answer.

No errors, file is saved correctly, just the TOC is not updated anymore...
I followed that and I have the new user settings format.

**Comment by naokazuterada** [comment]
OK, I want to more information.
Could you write down your document here ?

**Comment by lguerard** [comment]
Oops sorry I figured out the issue.

The file was saved as mkdown, which works for Markdown but doesn't update the TOC. Saving it as mdown fixed it. :+1:

**Comment by naokazuterada** [comment]
Oh, happy to hear that!
Please close this issue, thanks.
