### ISSUE TITLE
Auto generate link for _emphasized_ headings (TOC of README broken)

### ISSUE THREAD

**Issue by mpvharmelen** [naokazuterada/MarkdownTOC#129]
# How can the issue be reproduced
Try to click "Auto linking for clickable TOC" in the README.md of commit afe002a.

# What was expected
To jump to `#auto-linking-for-clickable-toc`

# What actually occurred
`#auto-linking-for-_clickable_-toc` was added to the url and nothing jumped.

# What was the version of the involved component
afe002a

**Comment by naokazuterada** [comment]
@mpvharmelen 
Hi, I'm so sorry for late reply 😭 
And thanks for your report, the link was dead certainly.
I will fix it ASAP.

**Comment by naokazuterada** [comment]
@mpvharmelen 
I found the 'markdown_preview' attribute was missing on README.
