### ISSUE TITLE
MarkdownTOC as a Standalone Python Plugin

### ISSUE THREAD

**Issue by artoric** [naokazuterada/MarkdownTOC#132]
@naokazuterada, thank you for the great plugin!
-Would be possible to *port* the plugin to the standalone python / command line version?
# Purpose
It would be really great to execute it from the command line and insert/update/remove [TOC] in any editor or markdown documents.
# How important it is
For me personally very important, since my favourite markdown editor (Ulysses) doesn't support TOCs.
# Ideal implementation
Thank you & cheers!

**Comment by naokazuterada** [comment]
Hi, @artoric 

I'm sorry but this plugin has strong dependencies on SublimeText API. So I can't make your wish come true.
You may try CLI tools first, as I think plugins for specific editors often depend on their APIs.

- https://github.com/rasbt/markdown-toclify (python)
- https://github.com/thlorenz/doctoc (node)

I close this issue, but I hope you to find a good solution 😃
