### ISSUE TITLE
Having a "-" in the heading breaks the autolink feature:

### ISSUE THREAD

**Issue by TheBestPessimist** [naokazuterada/MarkdownTOC#137]
# How can the issue be reproduced

It seems that having a "-" in the heading breaks the autolink feature:

```markdown
# ID Server - Migration Script

sometext
```
If the "-" above is deleted, the link works

# What was expected

Links work.

# What actually occurred

Clicking a link in the toc to go to the heading didn't work
# What was the version of the involved component

3.0.4

See example file: 
[a.md.txt](https://github.com/naokazuterada/MarkdownTOC/files/3058122/a.md.txt)

**Comment by naokazuterada** [comment]
Thanks again for reporting.

Markdown TOC create id(`#id-server---migration-script`) for heading  'ID Server - Migration Script'.
And [it works on Github](https://github.com/naokazuterada/MarkdownTOC-Tests/blob/master/example-for-137.md).

Please let me know your presentation environment (Gitlab, Marked2, etc.) and also id string you expected(Please check source code of HTML).

**Comment by naokazuterada** [comment]
Though it's an ugly workaround, you can avoid it with ["Manipulation of auto-link ids" feature](https://github.com/naokazuterada/MarkdownTOC#manipulation-of-auto-link-ids)

Add this into your configuration.
```json
{
  "pattern": "-",
  "replacement": ""
}
```

**Comment by naokazuterada** [comment]
Though this is an ugly workaround, you can avoid it with "Manipulation of auto-link ids" feature.

Add this into your configuration.
```json
"id_replacements": [
  {
    "pattern": "---",
    "replacement": "-"
  }
]
```
this changes `#id-server---migration-script` to `#id-server-migration-script`

**Comment by TheBestPessimist** [comment]
> Please let me know your presentation environment

I'm sorry, but idk what to show you. Can you give me details/steps?

I just edit my **HUGE** markdown file, then press <kbd>ctrl</kbd><kbd>B</kbd> and a tab is opened into chrome with the contents of my markdown as html.

**Comment by TheBestPessimist** [comment]
Yes, it seems that i have configured Markdown Preview only halfway.
As per the docs https://facelessuser.github.io/MarkdownPreview/usage/
after i added
```
github_inject_header_ids": true,
```
Those links work nicely!

Sorry for wasting your time on this :(

**Comment by naokazuterada** [comment]
@TheBestPessimist 
Oh, sorry for my bad English. I mean 'What do you use for rendering markdown as HTML?'.
So you showed me the right answer I want to know.

> MarkdownPreview

And sorry I forgot the link too.
[Manipulation of auto-link ids](https://github.com/naokazuterada/MarkdownTOC#manipulation-of-auto-link-ids)

I'm happy to hear that you solved!
And thanks for showing me your solution.

BTW, this plugin also has [Markdown Preview compatible](https://github.com/naokazuterada/MarkdownTOC#markdown-preview-compatible) feature.
So please choose from two solutions. (MarkdownTOC's config or Markdown Preview's)

**Comment by TheBestPessimist** [comment]
> BTW, this plugin also has [Markdown Preview compatible](https://github.com/naokazuterada/MarkdownTOC#markdown-preview-compatible) feature.

Yeah, seems like i missed that (though i did read the whole readme file. 😊 )

**Comment by jonasbn** [comment]
hi @naokazuterada @TheBestPessimist 

Was there something, in need of clarified in the documentation for **MarkdownTOC** ?

Or are there additions to [the compatility matrix](https://github.com/naokazuterada/MarkdownTOC#compatibility?

jonasbn

**Comment by naokazuterada** [comment]
@jonasbn Thank you for asking!
I think it's already enough.
