### ISSUE TITLE
Ignore comments in blocks of code

### ISSUE THREAD

**Issue by tapia** [naokazuterada/MarkdownTOC#146]
If you write some markdown like this:

    ```python
    # some comment
    ```

The comment is correctly ignored. But this is also valid markdown, and the comment is wrongly interpreted as a title:

    ~~~python
    # some comment
    ~~~

**Comment by naokazuterada** [comment]
This problem should be fixed in [4.0.1](https://github.com/naokazuterada/MarkdownTOC/releases/tag/4.0.1).
