### ISSUE TITLE
Markdown Preview compatible: Markdown

### ISSUE THREAD

**Issue by anlv** [naokazuterada/MarkdownTOC#147]
# How can the issue be reproduced

``` 
markdown_preview="markdown" and autolink="true"
```

has 2 same headers in content.

example:
```
## 05/05/2020
some text
## 05/05/2020
```

# What was expected

TOC should be:
```
- [05/05/2020](#05052020)
- [05/05/2020](#05052020_1)
```

# What actually occurred
```
- [05/05/2020](#05052020)
- [05/05/2020](#05052020-1)
```

The difference is the _ and - character on the second link #05052020_1 and #05052020-1

# What was the version of the involved component
markdownTOC: v4.0.1
MarkdownPreview: v2.2.5

**Comment by naokazuterada** [comment]
@anlv 
Thank you for reporting and sorry for late reply.
This problem may be fixed in [4.0.2](https://github.com/naokazuterada/MarkdownTOC/releases/tag/4.0.2).
Please check.
