### ISSUE TITLE
Add support for .mdx files

### ISSUE THREAD

**Issue by brophdawg11** [naokazuterada/MarkdownTOC#160]
# Purpose
Add support for auto-update in `.mdx` files used in Storybook: https://storybook.js.org/docs/react/api/mdx

# How important it is
Medium - you can add TOC's but they don't auto-update on save so they get out of sync

# Ideal implementation
I think it's as easy as updating https://github.com/naokazuterada/MarkdownTOC/blob/master/markdowntoc/autorunner.py#L10, but I'm not sure how to test locally

**Comment by naokazuterada** [comment]
@brophdawg11 Sorry for late reply and reaction. Now it released as [4.1.2](https://github.com/naokazuterada/MarkdownTOC/releases/tag/4.1.2)
