### ISSUE TITLE
QUESTION: link of different MD file into one MD file collected by TOC

### ISSUE THREAD

**Issue by kia13nn** [naokazuterada/MarkdownTOC#162]
# Question
Is it possible to have a document MD with a ToC capable of linking to different/several other MD files?

For example:
* ReferenceToC.md --> md document with a ToC that links to the other md files
   * path: F:\folderMAIN\ReferenceToC.md
*  file1.md  ;
   * path: F:\folderMAIN\folderFile1\file1.md
*  file2.md ;
   *  path: F:\folderMAIN\folderFile2\file2.md

Any idea or suggestions on how to solve something like this?
Thanks for your attention and dedicated time!

**Comment by naokazuterada** [comment]
@kia13nn MarkdownTOC can create TOC only for same document, sorry.
