### ISSUE TITLE
Broken for a while now

### ISSUE THREAD

**Issue by Gabriel-p** [naokazuterada/MarkdownTOC#168]
# How can the issue be reproduced
No TOC is generated anymore. 

Sublime Text 4152

# What was expected

# What actually occurred

# What was the version of the involved component

**Comment by 0xdevalias** [comment]
I just tried this on Sublime Text 4169 and it seems to be working for me (at least for manually inserting/updating the TOC)

**Potentially related:**

- https://github.com/naokazuterada/MarkdownTOC/issues/157
- https://github.com/naokazuterada/MarkdownTOC/issues/165
- https://github.com/naokazuterada/MarkdownTOC/issues/166

**Comment by Gabriel-p** [comment]
Seems to be working fine now , Build 4180
