### ISSUE TITLE
Editing disabled after usage

### ISSUE THREAD

**Issue by nrichards** [naokazuterada/MarkdownTOC#33]
Text insertion / deletion is disabled for my Markdown document in Sublime Text after using either "Insert" or "Update". E.g. 
1. create simple document
2. use "insert toc" command
3. press letter "a"
4. >> NO letter "a" is inserted in document

Expected to be able to edit immediately after using TOC plugin.

To workaround, initiate a "Find" command (Command + F) then cancel it (ESC).

Using current release build of ST 3.

**Comment by jonasbn** [comment]
Hi @naokazuterada,

The author of this issue have been unresponsive and you have not been able to replicate the issue and similar issues have not been reported - I recommend this issues being closed.

**Comment by naokazuterada** [comment]
OK, I close this.
@jonasbn Thank you!
