### ISSUE TITLE
Looks like something changed .. now getting following error on Insert TOC ..

### ISSUE THREAD

**Issue by pradeepkr103** [naokazuterada/MarkdownTOC#38]
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./MarkdownTOC.py", line 36, in run
  File "./MarkdownTOC.py", line 123, in get_toc
RuntimeError: Missing } in quantified repetition.  The error occured while parsing the regular expression fragment: '=+)$|^#{1,>>>HERE>>>None}[^#]'. in regular expression ^.*?(?:(?:
)|
|
)(?:-+|=+)$|^#{1,None}[^#]

line 123(and around it ) ... this is straight from github version pulled 15' ago. ..

    # TODO: add "end" parameter
    def get_toc(self, attrs, begin):

        # Search headings in docment
        if attrs['depth'] == 0:
            pattern_hash = "^#+?[^#]"
        else:
            pattern_hash = "^#{1," + str(attrs['depth']) + "}[^#]"
        headings = self.view.find_all(
            "%s|%s" % (pattern_h1_h2_equal_dash, pattern_hash))  # <-- line 123 is here ..

        headings = self.remove_items_in_codeblock(headings)

**Comment by naokazuterada** [comment]
I'm not sure, but I push a adjustment now.
Or would you try re-install this plugin? It has updated last weekend, and `MarkdownTOC.sublime-settings` should be updated.

**Comment by pradeepkr103** [comment]
I had previously uninstalled, then reinstalled the package and error was
there, so I put up a new issue.

I redid it just now, and insert TOC works now.

Thanks,

---- Pradeep Kumar
Go Mobile First
*Mobile & Web Architect *
LinkedIn:  www.linkedin.com/in/pradeepkjain/

**Comment by naokazuterada** [comment]
> I had previously uninstalled, then reinstalled the package and error was there, so I put up a new issue.

I see. I think [this commit](https://github.com/naokazuterada/MarkdownTOC/commit/4d7e213f13ea12ee92f0d51d27d924d89e81accb) fixed your issue maybe...

Anyway, thank you for your reporting.
