### ISSUE TITLE
Don't change case in Auto-link feature

### ISSUE THREAD

**Issue by michfield** [naokazuterada/MarkdownTOC#40]
Is it possible to add one more configuration option?
Almost everything can be customized, except that auto-anchors are lowercase.
Can you make that optional? With one simple flag in settings?

I need auto-anchors like "One_Two_Three", and not like "one_two_three".
Thanks in advance.

**Comment by naokazuterada** [comment]
It may be technically possible. But I want to know why you need it. Would you mind explaining your situation ?

**Comment by michfield** [comment]
I am using https://github.com/Dynalon/mdwiki to present my `.md` files.

Please note that I also asked for the similar request (reversed) on that project,
because it looks like `one-two-three` is standard.

**Comment by maliayas** [comment]
It should not lowercase `[^A-Z]`. Currently when it lowercases `İ` (which is not ASCII), it generates a `i` and an invisible character next to it.

**Comment by jonasbn** [comment]
Hi @naokazuterada 

I have labelled this as an new-feature, perhaps we should extract the observation by @maliayas as a bug report, so we do not have bugs/new-features mixed up in the same issue.

**Comment by naokazuterada** [comment]
This problem fixed on [2.6.0](https://github.com/naokazuterada/MarkdownTOC/releases/tag/2.6.0).
