### ISSUE TITLE
Allow the use of different list bullets for different levels

### ISSUE THREAD

**Issue by osopolar** [naokazuterada/MarkdownTOC#41]
I would like to be able to define the list items used for the TOC for each level, like

``` md
* H1
  - H2
    + H3
      *  H4
```

It might be configurable like this

`"list_indent_bullets": ["*", "-", "+"]`

Where the first item ist for the first level, the second for the second and so on until the last one of the list and then it starts over from the beginning.

See also sublime text package [MarkdownEditing](/SublimeText-Markdown/MarkdownEditing) settings: mde.list_indent_bullets

**Comment by naokazuterada** [comment]
@osopolar 

Hi, this feature is available on [2.5.0](https://github.com/naokazuterada/MarkdownTOC/releases/tag/2.5.0).
And I will close this issue.

See [Customizable list bullets](https://github.com/naokazuterada/MarkdownTOC#customizable-list-bullets-in-toc) in the REDAME.

Thank you for your suggestion.
