### ISSUE TITLE
Adding TOC removes headings in the doc

### ISSUE THREAD

**Issue by clokman** [naokazuterada/MarkdownTOC#44]
When I add a TOC, some headings that the TOC points to are removed.

Here's a screencast:
http://screencast.com/t/kfbXiOt0J9K

**Comment by naokazuterada** [comment]
Sorry! This is bug related to 'Auto anchor' feature, but it takes time to fix.

You can avoid this issue if you add a linebreak before the heading.

ex.
```

# THIS HEADING WILL BE REMOVED
## ANOTHER HEADING

```

```

# THIS HEADING WILL NOT BE REMOVED

## ANOTHER HEADING

```

**Comment by clokman** [comment]
Thanks a lot for the workaround! Will look forward for a fix, but this will do for now.
