### ISSUE TITLE
Add Github TOC option?

### ISSUE THREAD

**Issue by Gabriel-p** [naokazuterada/MarkdownTOC#46]
Currently the package generates a TOC entry as:

    - [the section title][the-section-title]

Github's `README.md` files support the following format:

    - [the section title](#the-section-title)

the default way won't work. Couldn't an option be added to generate TOC's using Github's format?

**Comment by naokazuterada** [comment]
Change the TOC open tag
```
<!-- MarkdownTOC -->
```
to
```
<!-- MarkdownTOC bracket=round -->
```
then, the plugin generate github format. Please see [here].(https://github.com/naokazuterada/MarkdownTOC#bracket)

**Comment by Gabriel-p** [comment]
Did not see that option. Thank you!
