### ISSUE TITLE
Autolinking isn't working

### ISSUE THREAD

**Issue by alxrz** [naokazuterada/MarkdownTOC#48]
Hi!

I've just downloaded a plugin to my sublime text 3 via package control. It seems that autolinking isn't correctly  working, looks like a bug, here's what I have generated:

```
- [a][a]
	- [b][b]
	- [c][c]
		- [d][d]
		- [e][e]
```

shouldn't it be like `[a](#a)`? and my custom settings are:

```
{
  "default_autolink": true,
  "default_depth": 3,
  "default_autoanchor": true
}
```

Thank you!.

**Comment by longle255** [comment]
+1 
I got this problem too

**Comment by MrLeeh** [comment]
Try the following setting:
```json
{
  "default_bracket": "round"
}
```

**Comment by naokazuterada** [comment]
Sorry for late reply.
Please try @MrLeeh 's setting, or see ["Bracket"](https://github.com/naokazuterada/MarkdownTOC#bracket) feature.
