### ISSUE TITLE
Allow custom string before TOC links

### ISSUE THREAD

**Issue by nicholaelaw** [naokazuterada/MarkdownTOC#50]
Hi there I want to suggest an option to insert a custom string into the TOC links.

Generally, the links are fine: `[Section](#section)` points to the heading "Section".

But my articles are also listed on an index page, and the TOC is visible on the index page. When shown on the index page, the TOC links would not work because they point to a non-existent heading.

I'd like to be able to add a string, `{{site.baseurl}}{{page.url}}/` to the link, so that the TOC link would look like

`[Section]({{site.baseurl}}{{page.url}}/#section)`

Then when clicked on the index page the link would point to the correct position in the article.

**Comment by naokazuterada** [comment]
Thank you for your suggestion and sorry for very late reply.

I don't want to add features more than necessary.
You should replace urls when you need it. Very simple.

So I close this. :bow:
