### ISSUE TITLE
ValueError when setting autoanchor to true

### ISSUE THREAD

**Issue by DRL** [naokazuterada/MarkdownTOC#60]
Hi, 

I am using sublime text 2.0.2 with the following MarkdownTOC.sublime-settings:

```
{
  "default_autolink": true,
  "default_bracket": "round",
  "default_depth": 0,
  "id_replacements": {
    "-": " ",
    "" : ["!","#","$","&","'","(",")","*","+",",","/",":",";","=","?","@","[","]","`","\"", ".","<",">","{","}","™","®","©"]
  },
  "default_autoanchor": true,
  "default_style": "ordered"
}
```

TOC gets built with "default_autoanchor" : false, but when setting it to true, the following output appears in the console:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./MarkdownTOC.py", line 40, in run
    toc += self.get_toc(attrs, sel.end(), edit)
  File "./MarkdownTOC.py", line 232, in get_toc
    self.update_anchors(edit, items, bool(attrs['autoanchor']))
  File "./MarkdownTOC.py", line 248, in update_anchors
    new_anchor = '\n<a name="{}"></a>'.format(item[3])
ValueError: zero length field name in format
```

Any help would be appreciated.

cheers, 

dom

**Comment by jonasbn** [comment]
Hi @DRL on what platform do you experience this error?

jonasbn

**Comment by jonasbn** [comment]
Hi @naokazuterada,

It the plugin still supporting Sublime Text version 2?

**Comment by naokazuterada** [comment]
@jonasbn Now ST2 is not supported, but this issue created before dropped ST2 support. 

I think it's ok to close this issue, because the implementation on this part has been updated.

**Comment by jonasbn** [comment]
Sounds reasonable to close it then
