### ISSUE TITLE
Auto-update on save for extensions other than .md

### ISSUE THREAD

**Issue by barredespace** [naokazuterada/MarkdownTOC#61]
I would very much like that my html files with markdown (and markdown TOC) inside would benefit from auto-updating on save… Or any other extension for that matter (pandoc insists on .markdown extension for example).
Thanks,
\--
Pascal

**Comment by naokazuterada** [comment]
This plugin support these extensions.

https://github.com/naokazuterada/MarkdownTOC/blob/master/MarkdownTOC.py#L352

What extension do you want to add?

**Comment by barredespace** [comment]
Oh. Sorry. I did not check for ` .markdown`.  
I just need `.html` please.

**Comment by naokazuterada** [comment]
I think your request is not good because `.html` is not a extension for markdown. MarkdownTOC is just for markdown files.

You can add `.html` to the list yourself.
