### ISSUE TITLE
list number incroee

### ISSUE THREAD

**Issue by helloyan** [naokazuterada/MarkdownTOC#62]
below is th toc , so you can see the problem

<pre>

1. [json交互时返回的通用格式](#json交互时返回的通用格式)
2. [各页面详细说明](#各页面详细说明)
    1. [首页](#首页)
        1. [功能说明](#功能说明)
        2. [场景](#场景)
            1. [打开](#打开)
    3. [产品搜索](#产品搜索)
        4. [功能说明](#功能说明-1)
        5. [场景](#场景-1)
            1. [打开](#打开-1)
    6. [注册登陆页](#注册登陆页)
        7. [功能说明](#功能说明-2)
        8. [场景](#场景-2)
            1. [打开](#打开-2)
            2. [用户名验证](#用户名验证)
            3. [登陆](#登陆)
            4. [验证码验证](#验证码验证)
            5. [注册](#注册)
            6. [忘记密码](#忘记密码)
    9. [详情页](#详情页)
        10. [功能说明](#功能说明-3)
        11. [场景](#场景-3)
            1. [打开](#打开-3)
            2. [供应商查询](#供应商查询)
            3. [产品评价](#产品评价)
    12. [ 二级类页](#-二级类页)
    2. [搜索结果页](#搜索结果页)
        1. [功能说明](#功能说明-4)
        2. [场景](#场景-4)
            1. [搜索](#搜索)

</pre>

**Comment by naokazuterada** [comment]
Sorry for late reply...

OK, I found the problem.

By the way, markdown has this counting feature itself. And I want to avoid conflict between this plugin's numbering and result of markdown rendering in this part. So I leave it to markdown rendering.


Before:
```
<!-- MarkdownTOC style=ordered -->

1. hoge
  1. hoge
    1. hoge
      1. hoge
      2. hoge
        1. hoge
    3. hoge
      4. hoge
      5. hoge
    2. hoge
      1. hoge
      2. hoge
        1. hoge
      3. hoge
      4. hoge
      5. hoge
        1. hoge
    6. hoge

<!-- /MarkdownTOC -->


# hoge
## hoge
### hoge
#### hoge
#### hoge
##### hoge
### hoge
#### hoge
#### hoge
### hoge
#### hoge
#### hoge
##### hoge
#### hoge
#### hoge
#### hoge
##### hoge
### hoge
```

After:
```

<!-- MarkdownTOC style=ordered -->

1. hoge
  1. hoge
    1. hoge
      1. hoge
      1. hoge
        1. hoge
    1. hoge
      1. hoge
      1. hoge
    1. hoge
      1. hoge
      1. hoge
        1. hoge
      1. hoge
      1. hoge
      1. hoge
        1. hoge
    1. hoge

<!-- /MarkdownTOC -->


# hoge
## hoge
### hoge
#### hoge
#### hoge
##### hoge
### hoge
#### hoge
#### hoge
### hoge
#### hoge
#### hoge
##### hoge
#### hoge
#### hoge
#### hoge
##### hoge
### hoge
```
