### ISSUE TITLE
Brush-up documentation

### ISSUE THREAD

**Issue by jonasbn** [naokazuterada/MarkdownTOC#69]
The documentation needs an overall brush-up. I have volunteered to take a lead on this.

**Comment by jonasbn** [comment]
Hola @naokazuterada, 

I have fleshed out a new documentation structure for the README. It is more feature centered than parameter/attribute centered. I am still fixing issues and cleaning the document.

All is available in the branch: https://github.com/naokazuterada/MarkdownTOC/tree/documentation_brush-up

Proof reading is most welcome, if I have gotten some features wrong, the examples are not valid.

There will be plenty of spelling errors and other issues, I will look into getting these addressed before a **possible** merge. 

Please let me know what you think

**Comment by naokazuterada** [comment]
Wow, thank you so much!
It looks good to me!

While I was reading, I noticed that it's not support ST2 in v2, and README's TOC style should be locked to be same result in different environments.

So please cherry pick these commits on master branch.

- c3672e5a67c373011ca6e82fa735daeb78cb3cb1
- b4ceb7536ad680b3766f3243ba966cb17e6baa07

**Comment by jonasbn** [comment]
Changes cherry-picked, you could just have checked out the branch, if I wanted to keep it private, I would not have published it 😄

**Comment by jonasbn** [comment]
I have added some more material, and added the following on my TODO list:

- [ ] Better examples, not clear on whether the use of examples named heading clutter the document, thinking search- and readability
- [ ] Add information on ST2 compatibility
- [ ] Add more information on other platforms than Apple OSX, where applicable (installation etc)
- [ ] More use cases / feature descriptions, hints and recommendations, lifted from issues raised
