### ISSUE TITLE
Ignore TOC updates in edit history ?

### ISSUE THREAD

**Issue by naokazuterada** [naokazuterada/MarkdownTOC#7]
⌘Zで戻る時に、TOCの更新も履歴に残っているので、気持ち悪いと思う人もいるかもしれない。どうしよう。

参考：begin_edit()
http://qiita.com/items/9427df9393ec5613c016

**Comment by naokazuterada** [comment]
Recording TOC updating in history is no problem. I changed my opinion, sorry.

**Comment by mustafa0x** [comment]
The automatic updating should not add entries to the undo/redo history
