### ISSUE TITLE
Lowercase non-latin chars breaks links in TOC on GitHub

### ISSUE THREAD

**Issue by lahmatiy** [naokazuterada/MarkdownTOC#72]
Currently plugin lowercases all chars. But GitHub lowercase latin chars only. Therefore links in TOC don't work if they contains non-latin chars.

Test case:

```md
## Пример Example
```

Expected TOC

```md
<!-- MarkdownTOC -->

- [Пример Example](#Пример-example)

<!-- /MarkdownTOC -->
```

Actual

```md
<!-- MarkdownTOC -->

- [Пример Example](#пример-example) <!-- broken link

<!-- /MarkdownTOC -->
```

It would be nice to fix it, or new option to setup behaviour – `"lowercase_non_latin": true/false`.

**Comment by naokazuterada** [comment]
Hi, @lahmatiy 

Thank you for your suggestion.I didn't notice it until your report.

I add new feature in [2.1.0](https://github.com/naokazuterada/MarkdownTOC/releases/tag/2.1.0)

Now you can make it possible by add `"default_lowercase_only_ascii": false` to your MarkdownTOC.sublime-settings or just add `lowercase_only_ascii=true` to TOC tag in your document.

See it on [README](https://github.com/naokazuterada/MarkdownTOC#lowercase-only-ascii-characters-in-auto-link-ids).

**Comment by naokazuterada** [comment]
Hi, @jonasbn 

[I updated README](https://github.com/naokazuterada/MarkdownTOC/commit/91be925caf3f1986391a2ea40daf8644a78798a6). Would you mind to confirm it?

**Comment by lahmatiy** [comment]
@naokazuterada Just tried updated plugin. Everything ok now with new setting. Thanks a lot!
