### ISSUE TITLE
 Analogue MarkdownTOC for HTML

### ISSUE THREAD

**Issue by Kristinita** [naokazuterada/MarkdownTOC#75]
You in the future would like to make analog of MarkdownTOC for HTML? I couldn't find in Google the plugins similar to yours, for HTML. At the [forum Sublime Text](https://forum.sublimetext.com/t/analogue-markdowntoc-for-html/21953) to me also nothing was prompted.

Thanks.

**Comment by naokazuterada** [comment]
Hi, @Kristinita 

I won't make 'MarkdownTOC for HTML' because I don't need it until now. Sorry... 😵 

How about to use this javascript? It seems like be easy to use.
https://github.com/matthewkastor/html-table-of-contents
