### ISSUE TITLE
Feature request: Provide easy way to remove TOC from a document

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [naokazuterada/MarkdownTOC#76]
If TOC is generated with hyperlinking enabled, the document will be inserted a lot of anchors. When removing the TOC, user would need to search and remove each of these by hand. For large documents this can be a lot of work.

The alternative is to generate the anchors with a unique identifier:
```
<a name="user-heading-1" id="mtoc"></a>
```

Later when user clicks on delete TOC, the table can be deleted along with all anchors having id mtoc.

**Comment by naokazuterada** [comment]
Thank you @Kshitiz-Sharma, it sounds nice! (maybe using 'data-xxx' attributes is better than 'id')

**Comment by jonasbn** [comment]
@naokazuterada let me know if you create a feature branch, then I will update the documentation accordingly in the same branch

Have a nice weekend,

jonasbn

**Comment by naokazuterada** [comment]
Hi @Kshitiz-Sharma 

Sorry, I noticed this feature has already been implemented.
Here is my screencast.

![remove-autoanchors](https://cloud.githubusercontent.com/assets/270925/18224035/84e5d85a-7203-11e6-91b4-5d3965303a75.gif)

It has been achieved in [this line](https://github.com/naokazuterada/MarkdownTOC/blob/master/MarkdownTOC.py#L234).

My test case is below. Please try it or report your condition in more detail.
```
<!-- MarkdownTOC autolink="true" autoanchor="false" -->

- [Changelog][changelog]
- [Glossary][glossary]
- [API Specification][api-specification]

<!-- /MarkdownTOC -->

# Changelog
Lorem ipsum...

# Glossary
Lorem ipsum...

# API Specification
Lorem ipsum...
```

**Comment by Kshitiz-Sharma** [comment]
Thanks. That should do. I'm closing this request.

**Comment by jonasbn** [comment]
Hi @naokazuterada do you want a mention of this in the documentation.

jonasbn

**Comment by naokazuterada** [comment]
Hello @jonasbn ,

I think it's not necessary. But it's nice that it's mentioned in the document naturally. Could you try?
Thank you a lot for your kindness.
