### ISSUE TITLE
Is it possible to render TOC markdown as HTML?

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [naokazuterada/MarkdownTOC#77]
Has HTML rendering been considered in mtoc's design? If not, do we have any plans to make it integrate better with the [Preview plugin](https://github.com/revolunet/sublimetext-markdown-preview)? 

Consider following markdown with TOC:
<img width="537" alt="markdown" src="https://cloud.githubusercontent.com/assets/6263572/18224421/69e1c9b0-71cc-11e6-8454-0aa803367f15.PNG">

On converting to HTML with Preview plugin it looks like this:
<img width="510" alt="result" src="https://cloud.githubusercontent.com/assets/6263572/18224422/69e469ae-71cc-11e6-89cf-781bad29b78f.PNG">

**Comment by naokazuterada** [comment]
Hi @Kshitiz-Sharma, sorry but I can't understand what you mean...(I'm poor at English 😵 )

Would you explain more detail? or in another way?

I'm not using  [Preview plugin](https://github.com/revolunet/sublimetext-markdown-preview).

**Comment by naokazuterada** [comment]
Is this your problem ? (red area in image below)
<img width="510" alt="69e469ae-71cc-11e6-89cf-781bad29b78f" src="https://cloud.githubusercontent.com/assets/270925/18269907/56ca1954-7465-11e6-92a1-d4bbf6612592.PNG">

**Comment by naokazuterada** [comment]
> Is it possible to render TOC markdown as HTML?

It's not possible.

This plugin does only 'making toc'. HTML rendering feature is out of this plugin's purpose so far.

**Comment by naokazuterada** [comment]
@Kshitiz-Sharma 

I found a way.  Use `bracket="round"` then the sublimetext-markdown-preview plugin render correctly.

```
<!-- MarkdownTOC autolink="true" bracket="round" -->

- [test](#test)

<!-- /MarkdownTOC -->


# test
```

Maybe the sublimetext-markdown-preview plugin doesn't support ["Markdown standard reference-style links"](http://daringfireball.net/projects/markdown/syntax#link). See also [this section](https://github.com/naokazuterada/MarkdownTOC#auto-linking-for-clickable-toc) of our document.
