### ISSUE TITLE
escaping &_acute and &_tilde

### ISSUE THREAD

**Issue by ghost** [naokazuterada/MarkdownTOC#79]
Even with `"default_lowercase_only_ascii": true`the only way to exclude Spanish "tildes" (Cami**ó**n, **ú**ltimo) and Espa**ñ**a was by adding one by one `id_replacements` for each letter. My user-settings look like this:

```
{
  "default_autolink": true,
  "default_bracket": "round",
  "default_depth": 2,
  "default_autoanchor": true,
  "default_lowercase_only_ascii": true,
  "default_style": "unordered",
  "id_replacements": {
    "-": " ",
    "a": ["&aacute", "á"],
    "e": ["&eacute", "é"],
    "i": ["&iacute", "í"],
    "o": ["&oacute", "ó"],
    "u": ["&uacute", "ú"],
    "A": ["&Aacute", "Á"],
    "E": ["&Eacute", "É"],
    "I": ["&Iacute", "Í"],
    "O": ["&Oacute", "Ó"],
    "U": ["&Uacute", "Ú"],
    "n": ["&ntilde", "ñ"],
    "N": ["&ntilde", "Ñ"],

    "" : ["&lt;","&gt;","&amp;","&apos;","&quot;","&#60;","&#62;","&#38;","&#39;","&#34;","!","#","$","&","'","(",")","*","+",",","/",":",";","=","?","@","[","]","`","\"", ".","<",">","{","}","™","®","©"]
    }

}
```

Any idea to make this more efficiently? There are still a bunch of "weird" characters that won't work as anchors in a html file.

**Comment by jonasbn** [comment]
hmmmm @naokazuterada is it possible to detect the encoding of the text/file in SL? - based on that a conversion could be made to a simpler format. I work with DNS and [punycode](https://en.wikipedia.org/wiki/Punycode) springs to mind as a solution to a somewhat similar problem.

**Comment by naokazuterada** [comment]
@ghost

I'm sooo sorry for late reply. 🤕 

Today I added a new feature [URI encoding](https://github.com/naokazuterada/MarkdownTOC#uri-encoding). And I saw all links are working correctly on Gitlab([sample](https://gitlab.com/naokazu.terada/MarkdownTOC-Tests/blob/f8f1f479589dcb02f9e1262e77a41b0d49f1985e/README.md)) and Github([sample](https://github.com/naokazuterada/MarkdownTOC-Tests/blob/b8f1c826b154d9d2a25608f081b31156cb5c2abd/README.md)).

I hope this fix your problem. 🦊  I'm looking forward to your response if you don't mind.

**Comment by jonasbn** [comment]
Hi @naokazuterada,

I recommend we close this issue, lets reopen if the issue persists. An expected fix has been implemented and shipped.

**Comment by naokazuterada** [comment]
@jonasbn OK, thanks. Close it.
