### ISSUE TITLE
support the toc on the top/left/right of the output xml, maybe that be cool.

### ISSUE THREAD

**Issue by shasky2014** [naokazuterada/MarkdownTOC#80]

**Comment by jonasbn** [comment]
Hello @shasky2014, I am not sure I understand what you mean, could you elaborate on your improvement suggestion?

jonasbn

**Comment by jonasbn** [comment]
@naokazuterada I do not understand this question, unless you can clarify I suggest for this issue to be closed.

**Comment by naokazuterada** [comment]
@jonasbn I'm not sure too...
OK, I close this.
