### ISSUE TITLE
Issue with Github pages: rendering of headers not working

### ISSUE THREAD

**Issue by jonasbn** [naokazuterada/MarkdownTOC#81]
I have been playing around with Github pages over the holiday and applying use of [Github pages](https://pages.github.com/) and [themes](https://github.com/pages-themes) is [easier than ever](https://github.com/blog/2289-publishing-with-github-pages-now-as-easy-as-1-2-3).

But it seems that the themes do not render heading of pages correctly, when  using **MarkdownTOC**.

See my [Today I Learned repository](http://jonasbn.github.io/til/) for example, I have tried other themes with the same result.

I suspect that the Markdown renderers are confused by the leading anchors. I am working on a fix, but I cannot run the unit-test suite as described in the contribution guidelines and the guide by randy3k - any advice most welcome:

```ERROR: Start directory is not importable: '/Users/jonasbn/Library/Application Support/Sublime Text 3/Packages/MarkdownTOC/tests'```

How do I get the unit-test suite to work on the Github repository instead of the installed package?

Merry x-mas,

jonasbn

**Comment by naokazuterada** [comment]
Why don't you set `autoanchor=false`?

> How do I get the unit-test suite to work on the Github repository instead of the installed package?

I have no idea, sorry. But this repository is integrate with [travis-ci.

**Comment by jonasbn** [comment]
Thanks @naokazuterada I will do some more experimentation :-)

**Comment by jonasbn** [comment]
Works like a charm - thanks
