### ISSUE TITLE
Remove the print statement

### ISSUE THREAD

**Issue by math2001** [naokazuterada/MarkdownTOC#85]
Hello!

First of all: thanks for your plugin, it saves me a lot of time!

I have a problem though: there is a print statement that outputs `'cannot find TOC tags'`. Each time I save a markdown file, this is printed. 

It's quite annoying as I'm building [MarkdownLivePreview](), the console is always open, and I have set `save_on_focus_lost` to `true`.

I don't see any use in this message being logged into the console. Maybe add a setting? (I already tweaked the code 😄 ).

Thanks again for your plugin,

Matt

**Comment by naokazuterada** [comment]
Hi @math2001 ,

Thank you for your suggestion!

Now I removed logging in default. If you want to see logging, [set `logging` option to `true`](https://github.com/naokazuterada/MarkdownTOC/blob/master/MarkdownTOC.sublime-settings#L13).

I am glad to have you used this plugin! 🤓

**Comment by math2001** [comment]
Cool, using a settings is much better!

Thank you!
