### ISSUE TITLE
The combination of the title and the list does not take effect, such as "+ ##"

### ISSUE THREAD

**Issue by zhilidali** [naokazuterada/MarkdownTOC#86]
Like this:
```
+ # abc
	+ ## aaa
	+ ## bbb
	+ ## ccc
+ # xyz
	+ xxx
	+ yyy
	+ zzz
```

**Comment by naokazuterada** [comment]
Yes. Heading in list doesn't appear in TOC.That's the specification.

**Comment by zhilidali** [comment]
@naokazuterada 
I have always thought that this is the limitation of markdown syntax

**Comment by naokazuterada** [comment]
I'm sorry about that. I close this.

**Comment by jonasbn** [comment]
Hi @naokazuterada 

I have created a PR (#92) with a new section on limitations of the **MarkdownTOC** plugin addressing the information above.

jonasbn
