### ISSUE TITLE
MarkdownTOC disabled right after installation

### ISSUE THREAD

**Issue by gsal** [naokazuterada/MarkdownTOC#87]
Say, just downloaded MarkdownTOC and installed in my instance of SublimeText 2; but, when it appeared, it turned out that options "Insert TOC"  and  "Update TOC" are disabled, grayed-out...any ideas how to solve this? 

thx

**Comment by naokazuterada** [comment]
Sorry, but this plugin doesn't support ST2. Please use ST3.
