### ISSUE TITLE
Is that possible to number the markdown's header

### ISSUE THREAD

**Issue by weituotian** [naokazuterada/MarkdownTOC#91]
like the project [markdown-number-md-header](https://github.com/luochenxun/markdown-number-md-header)

it is a important function optional to users!!!

**Comment by naokazuterada** [comment]
We have ['Ordered or unordered style for TOC elements' feature](https://github.com/naokazuterada/MarkdownTOC#ordered-or-unordered-style-for-toc-elements
), but header number is not our defensive range. sorry.

**Comment by weituotian** [comment]
@naokazuterada maybe you can add the header number, and default false to users

**Comment by naokazuterada** [comment]
Hmmm sorry. 🦊 
I think rewriting header is too much. This plugin is just support making TOC.

**Comment by weituotian** [comment]
@naokazuterada 
oh, is that hard to modify the headers with number? i am sorry about can not find a plugin to do that.

**Comment by naokazuterada** [comment]
Modifying the headers is possible technically, but it doesn't much plugin's ideal.
I want this plugin to be simple and low dependency for users.

**Comment by weituotian** [comment]
@naokazuterada does sublime text3 provide the api to replace the headers?

**Comment by naokazuterada** [comment]
Yes!

**Comment by weituotian** [comment]
@naokazuterada i am confused about what does the folder bs4 do in the code

**Comment by naokazuterada** [comment]
Oh sorry... I'm not sure but maybe you can remove it. I think I added it for new feature but it's not implemented... 🤕

**Comment by weituotian** [comment]
@naokazuterada may you write some code for me? i feel hard to modify the code, sadly.

**Comment by naokazuterada** [comment]
I think this method may helps you.
https://github.com/naokazuterada/MarkdownTOC/blob/master/MarkdownTOC.py#L219-L236

**Comment by weituotian** [comment]
finally i understand what link anchor means.

```
<a name="changelog"></a>
# Changelog
Lorem ipsum...

<a name="glossary"></a>
# Glossary
Lorem ipsum...

<a name="api-specification"></a>
# API Specification
Lorem ipsum...
```

@naokazuterada why there is a need to add an anchor ?

**Comment by weituotian** [comment]
@naokazuterada why you frequently use reversed, what does it want to do?

**Comment by weituotian** [comment]
@naokazuterada 

you should add this [repo ](https://github.com/weituotian/md_numbered_headers )in your readme.

this plugin fully compitiable with markdown toc.

it is a option to let people to choose what they want to do!

**Comment by naokazuterada** [comment]
@weituotian Sorry for late reply.
I will take a look at your plugin and think about your suggestion.
Anyway thank your for informing me!
