### ISSUE TITLE
Ignore ToC heading in ToC

### ISSUE THREAD

**Issue by RichardLitt** [naokazuterada/MarkdownTOC#98]
I have this ToC generated in Sublime using the plugin:

```md
...
## Table of Contents

<!-- TOC depthFrom:2 depthTo:6 withLinks:1 updateOnSave:1 orderedList:0 -->

- [Table of Contents](#table-of-contents)
...
```

Is there a way to not have Table of Contents referred to in the ToC? 

Accidentally also here: filed https://github.com/jonschlinkert/markdown-toc/issues/90.

**Comment by naokazuterada** [comment]
You maybe use another plugin.
See our [README.md](https://github.com/naokazuterada/MarkdownTOC#customizing-generation-of-toc-using-attributes), the syntax is different.

**Comment by RichardLitt** [comment]
Thank you.

**Comment by RichardLitt** [comment]
The bug reporting in Markdown-toc in Sublime leads me here. Can I just verify again that I'm not missing something?

<img width="1130" alt="screen shot 2017-06-27 at 11 14 01 pm" src="https://user-images.githubusercontent.com/910753/27619110-59c6535a-5b8e-11e7-821e-34c6656da77e.png">

**Comment by RichardLitt** [comment]
Yep, definitely not this one. My bad. Wow.

**Comment by naokazuterada** [comment]
I think you use Atom not SublimeText3... 🦊

**Comment by RichardLitt** [comment]
I think I was tired, and probably need to not post bug reports when I am sleepy. Really, my bad.
